name: design_system
description: "Design System Package"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

# Define the workspace
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  http: ^1.0.0
  carousel_slider: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
