name: network
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

# Define the workspace
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
